# Generated by Django 4.1 on 2022-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SwimmingResult",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sport", models.CharField(max_length=50, verbose_name="競技")),
                ("event", models.CharField(max_length=50, verbose_name="種目")),
                ("rank", models.SmallIntegerField(verbose_name="順位")),
                ("athletes", models.TextField(verbose_name="選手")),
                ("team", models.CharField(max_length=20, verbose_name="チーム")),
                ("record", models.CharField(max_length=20, verbose_name="記録")),
            ],
        ),
    ]
