# Generated by Django 4.1 on 2022-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swimmingresult",
            name="record",
            field=models.CharField(max_length=20, null=True, verbose_name="記録"),
        ),
    ]
