# Generated by Django 4.1 on 2022-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_alter_swimmingresult_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swimmingresult",
            name="record",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="記録"
            ),
        ),
    ]
